from __future__ import annotations

import os
from pathlib import Path

import pytz

SHANGHAI_TZ = pytz.timezone("Asia/Shanghai")
REQUEST_TIMEOUT = 30
DEFAULT_WIKIPEDIA_LANG = os.environ.get("WIKIPEDIA_LANG", "zh")
DEFAULT_LIMIT = int(os.environ.get("HISTORY_TODAY_LIMIT", "8"))
DEFAULT_OUTPUT_DIR = Path(os.environ.get("OUTPUT_DIR", "output"))
ASSET_ROOT = Path("assets") / "generated" / "history_today"
PRIMARY_GEMINI_MODEL = "gemini-3-flash-preview"
FALLBACK_GEMINI_MODEL = "gemini-3.1-flash-lite-preview"
SOURCE_BRITANNICA = "britannica"
SOURCE_WIKIMEDIA = "wikimedia"
SOURCE_DAYINHISTORY = "dayinhistory"
SOURCE_API_NINJAS = "api_ninjas"
SOURCE_HISTORY_DOT_COM = "history_dot_com"
UNSPLASH_SEARCH_URL = "https://api.unsplash.com/search/photos"
OPENVERSE_IMAGES_URL = "https://api.openverse.org/v1/images/"
COMMONS_API_URL = "https://commons.wikimedia.org/w/api.php"
MINIMAX_IMAGE_API_URL = "https://api.minimaxi.com/v1/image_generation"
MONTH_NAMES = {
    1: "january",
    2: "february",
    3: "march",
    4: "april",
    5: "may",
    6: "june",
    7: "july",
    8: "august",
    9: "september",
    10: "october",
    11: "november",
    12: "december",
}
CHINA_RELATED_PATTERNS = [
    "china",
    "chinese",
    "中国",
    "中华人民共和国",
    "中华民国",
    "中共",
    "中国共产党",
    "北京",
    "上海",
    "广州",
    "深圳",
    "武汉",
    "香港",
    "澳门",
    "台湾",
    "台北",
    "西藏",
    "新疆",
    "内蒙古",
    "满洲",
    "清朝",
    "明朝",
    "元朝",
    "汉朝",
    "唐朝",
    "宋朝",
    "people's republic of china",
    "republic of china",
    "prc",
    "roc",
    "communist party of china",
    "chinese communist party",
    "ccp",
    "cpc",
    "mao zedong",
    "xi jinping",
    "deng xiaoping",
    "chiang kai-shek",
    "sun yat-sen",
    "beijing",
    "peking",
    "shanghai",
    "guangzhou",
    "shenzhen",
    "wuhan",
    "hong kong",
    "macau",
    "taiwan",
    "taipei",
    "tibet",
    "xinjiang",
    "inner mongolia",
    "manchuria",
    "uyghur",
    "uygur",
    "tiananmen",
    "south china sea",
    "pla",
    "kuomintang",
    "nationalist china",
    "qing dynasty",
    "ming dynasty",
    "yuan dynasty",
    "han dynasty",
    "tang dynasty",
    "song dynasty",
    "taiwan strait",
    "formosa",
    "taiwanese",
    "chiang ching-kuo",
    "lee teng-hui",
    "chen shui-bian",
    "ma ying-jeou",
    "tsai ing-wen",
    "democratic progressive party",
    "nationalist government",
    "warlord era",
    "first sino-japanese war",
    "second sino-japanese war",
    "boxer rebellion",
    "xinhai revolution",
    "beiyang",
    "qing empire",
    "puyi",
    "yuan shikai",
]

SENSITIVE_TOPIC_PATTERNS = [
    "politics",
    "political",
    "territorial dispute",
    "territorial disputes",
    "border dispute",
    "border conflicts",
    "sovereignty",
    "sovereign claim",
    "annexation",
    "cession",
    "secession",
    "independence movement",
    "independence referendum",
    "separatist",
    "self-determination",
    "civil war",
    "coup",
    "military junta",
    "regime",
    "party congress",
    "communist party",
    "nationalist party",
    "election",
    "referendum",
    "protest movement",
    "occupation of",
    "occupied territory",
    "disputed territory",
    "uprising",
    "rebellion",
    "revolution",
    "martial law",
    "colonial rule",
    "colonial government",
    "geopolitical",
    "sanction",
    "diplomatic crisis",
    "ethnic conflict",
]
